# Generated by Django 5.2 on 2025-04-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuaderno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('apuntes', models.TextField(null=True)),
                ('puntuacion', models.IntegerField()),
            ],
        ),
    ]
